name: 'Magento 2 PHPStan'
description: 'Performs PHP static code analysis with the Magento 2 PHPStan ruleset'
inputs:
  app_code_path:
    description: 'Path to do code analysis'
    required: true
  phpstan_config_file: 
    description: 'Path to PHPStand configuration file'
    default: 'dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon'
    required: false
  phpstan_level:
    description: 'PHPStan level to check. 1 by default.'
    default: '1'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'

